### PR TITLE
a  bit of a change

### PR DESCRIPTION
**Pull request by soudblox**
i change some triggers and i change the rob cmd a little bit, i fix some errors because the {{els e}} and i make it so it says You failed robbing @user instead of You failed someone

### CODE REVIEW

**Comment by JordiHakimZiyech** [comment]
Seems fine but, i'm gonna merge steal/rob, withdraw and deposit to 1 command anyways

**Comment by soudblox** [comment]
well, then use my rob when merging :ye:

**Review by JordiHakimZiyech — CHANGES_REQUESTED** [review]
At bal.go.tmpl: please change the text
it says  trigger type: command, should be regex

**Comment by soudblox** [comment]
done e.e

**Pull request merged**
